name: 🤖 Run CVEmap

on:
  workflow_dispatch:

jobs:
  run-cvemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Set up Go 1.21 environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      
      # Install cvemap
      - name: Install CVEmap
        run: go install github.com/projectdiscovery/cvemap/cmd/cvemap@fa6eb96
      
      # Run cvemap with JSON output and specific criteria
      - name: Run CVEmap with ID filter
        run: |
          echo "Running CVEmap with JSON output"
          cvemap -json
            echo "Running CVEmap without JSON output"
          cvemap -l 5
        env:
          PATH: ${{ github.workspace }}/go/bin:$PATH
          PDCP_API_KEY: ${{ secrets.PDCP_API_KEY }}
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3