name: Nuclei Sarif

on:
    workflow_dispatch:

permissions:
  issues: write
  security-events: write

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Nuclei - Vulnerability Scan 1
        id: nuclei_scan_1
        uses: projectdiscovery/nuclei-action@issue-85-sarif-file-not-exist
        with:
          target: https://example.com
          flags: "-v -debug"
          templates: custom-templates/no-match-test.yaml
          report-config: github-report.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub Security Dashboard Alerts update for scan 1
        if: steps.nuclei_scan_1.outputs.sarif_exists == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: nuclei.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Nuclei - Vulnerability Scan 2
        id: nuclei_scan_2
        uses: projectdiscovery/nuclei-action@issue-85-sarif-file-not-exist
        with:
            target: https://example.com
            flags: "-v -debug"
            templates: custom-templates/test.yaml
            report-config: github-report.yml
            github-token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: GitHub Security Dashboard Alerts update for scan 2
        if: steps.nuclei_scan_2.outputs.sarif_exists == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
            sarif_file: nuclei.sarif
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

