name: Nuclei Sarif

on:
    workflow_dispatch:

permissions:
  issues: write

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: https://example.com
          flags: "-v -debug"
          templates: custom-templates/test.yaml
          report-config: github-report.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: custom-templates/nuclei.sarif