name: 🤖 Nuclei Action

on:
  workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Nuclei - Vulnerability Scan - with projectdiscovery/main (existing)
          uses:  projectdiscovery/nuclei-action@main
          with:
            target: https://example.com
            flags: "-rate-limit 10 -max-retries 10"
            templates: custom-templates/test.yaml
        
        - name: Nuclei - Vulnerability Scan - with single flag (test)
          uses:  felipesaezreyes/nuclei-action@fix-flags-regex
          with:
            target: https://example.com
            flags: "-rate-limit 5"
            templates: custom-templates/test.yaml

        - name: Nuclei - Vulnerability Scan - with multiple flags 2 (test)
          uses:  felipesaezreyes/nuclei-action@fix-flags-regex
          with:
            target: https://example.com
            flags: "-rate-limit 5 -max-retries 2"
            templates: custom-templates/test.yaml

        - name: Nuclei - Vulnerability Scan - with multiple flags (test)
          uses:  felipesaezreyes/nuclei-action@fix-flags-regex
          with:
            target: https://example.com
            flags: "-rate-limit 10 -max-retries 2"
            templates: custom-templates/test.yaml

        # - name: Debug with tmate session
        #   uses: mxschmitt/action-tmate@v3