name: 🤖 Nuclei Action Fisehara

on:
  workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Nuclei - Vulnerability Scan - with projectdiscovery/main (existing)
          uses:  projectdiscovery/nuclei-action@main
          with:
            target: https://example.com
            report-config: issues.yml
            templates: custom-templates/test.yaml
            github-token: ${{ secrets.GITHUB_TOKEN }}

        # - name: Debug with tmate session
        #   uses: mxschmitt/action-tmate@v3