name: 🤖 Nuclei Action

on:
  workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        
        - name: Nuclei - Vulnerability Scan
          uses: PittyXu/nuclei-action@main
          with:
            target: https://example.com
            workflows: custom-worlfows/custom-workflow.yaml

        - name: Nuclei - Vulnerability Scan 2
          uses: PittyXu/nuclei-action@main
          with:
            target: https://example.com
            workflows: custom-worlfows/custom-workflow.yaml
        
        # - name: Debug with tmate session
        #   uses: mxschmitt/action-tmate@v3