name: 🤖 Nuclei Action Test

on:
  workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Nuclei - Vulnerability Scan - with projectdiscovery/main (existing)
          uses:  projectdiscovery/nuclei-action@main
          with:
            target: https://example.com
            templates: custom-templates/test.yaml
            report-config: github-report.yml # without github username,token config fields...
          continue-on-error: true

        - name: Nuclei - Vulnerability Scan - with fisehara/merge-github-report-config-files (new)
          uses:  fisehara/nuclei-action@fisehara/merge-github-report-config-files
          with:
            target: https://example.com
            templates: custom-templates/test.yaml
            report-config: github-report.yml # without github owner,token config fields...
            github-token: ${{ secrets.GITHUB_TOKEN }}
        
        # - name: Nuclei - Vulnerability Scan - with multiple flags (test)
        #   uses:  felipesaezreyes/nuclei-action@fix-flags-regex
        #   with:
        #     target: https://example.com
        #     flags: "-rate-limit 10 -mhe 2"
        #     templates: custom-templates/test.yaml

        # - name: Debug with tmate session
        #   uses: mxschmitt/action-tmate@v3