name: 🤖 Nuclei Action

on:
  workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        
        - name: Nuclei - Vulnerability Scan
          uses:  projectdiscovery/nuclei-action@main
          with:
            target: https://qa.redacted.com
            flags: "-rate-limit 10"
            workflows: custom-worlfows/custom-workflow.yaml
        
        # - name: Debug with tmate session
        #   uses: mxschmitt/action-tmate@v3