name: Nuclei Sarif

on:
    workflow_dispatch:

permissions:
  issues: write
  security-events: write

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Nuclei - Vulnerability Scan 2
        id: nuclei_scan
        uses: projectdiscovery/nuclei-action@issue-53-replace-func-undefined-err
        with:
            target: https://example.com
            flags: "-v -debug"
            templates: custom-templates/test.yaml
            report-config: github-report.yml
            github-token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: GitHub Security Dashboard Alerts update
        if: steps.nuclei_scan.outputs.sarif_exists == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
            sarif_file: nuclei.sarif
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

