name: 🤖 TemplateMan

on:
  push:
    branches:
      - main
      - templateman-workflow
    paths:
      - '**.yaml'
  workflow_dispatch:

jobs:
  templateman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x

      - name: Debug ACCESS_TOKEN
        run: echo "${{ secrets.ACCESS_TOKEN }}"
        
      - name: Install TemplateMan CLI Client
        run: |
          git clone https://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@github.com/RamanaReddy0M/templateman.git
          cd templateman/templateman-cli/cmd/tmc
          go install

      - name: Run TemplateMan
        id: tmc
        run: |
          tmc -t /home/runner/work/nuclei-templates/nuclei-templates/http/technologies -mr -e
          ls /home/runner/work/nuclei-templates/nuclei-templates/http/technologies
          git status -s | wc -l | xargs -I {} echo CHANGES={} >> $GITHUB_ENV

      - name: Commit files
        if: steps.tmc.outputs.CHANGES > 0
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "TemplateMan Update [$(date)] :robot:" -a

      - name: Push changes
        if: steps.tmc.outputs.CHANGES > 0
        run: |
          git pull --rebase
          git push origin ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
