name: Go on Windows

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.3

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go get -v -t -d ./...
      shell: pwsh
    
    - name: Debug with tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Build
      run: go build -v ./...
      shell: pwsh

